name: Start
on:
  push:
    branches:
      - main

jobs:
  auto-setup:
    defaults:
      run:
        shell: bash -i {0}
    runs-on: ubuntu-latest

    if: github.event.repository.name != 'start-android'

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # otherwise, you could failed to push refs to dest repo

      - name: Checkout template
        uses: actions/checkout@v2
        with:
          repository: 'omarmiatello/android-template'
          path: 'project-templates'

      - name: Install sdkman
        run: curl -s "https://get.sdkman.io" | bash

      - name: Install kotlin
        run: sdk install kotlin

      - name: Install kscript
        run: sdk install kscript

      - name: Run script
        run: kscript start.kt

      # Commit modified files
      - name: Commit files
        run: |
          rm -r project-templates
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Setup using android-template - by https://github.com/omarmiatello/start-android"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          branch: ${{ github.ref }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
